### ISSUE TITLE
Issues found to fix

### ISSUE THREAD

**Issue by tote93** [tote93/TMDB-Film-Database#11]
- Mixed dependencies and devDependencies

- Mixed imports

- Can't search certain chars

- Delete Useless comments

- Detail uses only data from the index

- Detail selected through custom flux implementation without the possibility to deep-link even though uses React Router

- No API layer

- Using filter(...)[0] instead of find(...)
Instead of directly passing movie object into onClick handler it uses alt text of clicked image to filter (instead of find) the whole collection

- Unnecessary null coalescing operators

- Repeated code

**Comment by MounicaChanda0809** [comment]
Working on this

**Comment by MounicaChanda0809** [comment]
Can you please add "hacktoberfest" topic to your repository? Please that way it counts towards my PR challenge
